### ISSUE TITLE
How to configure this package for L5.2

### ISSUE THREAD

**Issue by karnash** [Bogardo/Mailgun#102]
hi i try to follow the readme info to use this package but i can't achieve makes it work please could someone upload a full example please. thk

**Comment by Bogardo** [comment]
Could you please specify what exactly is causing the issues?
Installing the package?
Registering the ServiceProvider?
Registering the HTTP Client?

**Comment by karnash** [comment]
install                --- > ok
serviceProvides ---> X
httpCliente        --->X
 i need a full example please to how use and config the laravel and use Mailgun class, because i can`t call the `Mailgun::send()`

**Comment by Bogardo** [comment]
So to confirm, you have installed the package using: `composer require bogardo/mailgun`.
Next, you need to open your `config/app.php` file and look for the `providers` key in the array.
Within that array you need to add the MailgunServiceProvider reference.

```php
'providers' => [
    ...
    Bogardo\Mailgun\MailgunServiceProvider::class

];
```

In the same file, when you scroll down you'll find the `aliases` key. 
Within that array you need to add the Mailgun Facade reference.

```php
'aliases' => [
    ...
    'Mailgun' => Bogardo\Mailgun\Facades\Mailgun::class
],
```

Next, run the following command in your terminal:
```bash
php artisan vendor:publish --provider="Bogardo\Mailgun\MailgunServiceProvider" --tag="config"
```

This will create a new file `config/mailgun.php`.

**Comment by Bogardo** [comment]
The last part is setting up your HTTP Client. It may seem rather difficult but it really isn't.
Just install `php-http/guzzle6-adapter` with composer.

```bash
composer require php-http/guzzle6-adapter
```

When that is finished open the file `app/Providers/AppServiceProvider.php` and add the following to the `register` method:

```php
$this->app->bind('mailgun.client', function() {
    $client = new \GuzzleHttp\Client([]);
    return new \Http\Adapter\Guzzle6\Client($client);
});
```

**Comment by karnash** [comment]
all ok but when i run the publish i have 

![image](https://cloud.githubusercontent.com/assets/5040782/23215129/ac3f9bb4-f8e7-11e6-972f-2b8871c2c207.png)

**Comment by Bogardo** [comment]
Try clearing your config cache and try again:

```bash
php artisan config:clear
php artisan vendor:publish --provider="Bogardo\Mailgun\MailgunServiceProvider" --tag="config"
```

**Comment by karnash** [comment]
my Appserviceprovider
![image](https://cloud.githubusercontent.com/assets/5040782/23215217/f80c1158-f8e7-11e6-90b1-b8b60e73658f.png)

**Comment by karnash** [comment]
result to clear config
![image](https://cloud.githubusercontent.com/assets/5040782/23215284/2f44794e-f8e8-11e6-8a01-eeacdc6635fd.png)

**Comment by Bogardo** [comment]
You need to add your `domain` and `secret` to the `config/mailgun.php` file.

**Comment by Bogardo** [comment]
Which version of Laravel are you using?

**Comment by karnash** [comment]
Laravel 5.2
![image](https://cloud.githubusercontent.com/assets/5040782/23215328/5d40b2f4-f8e8-11e6-870f-fd6701ba8c20.png)

**Comment by Bogardo** [comment]
You could try running:

```bash
php artisan vendor:publish
```

Just note that this command may copy more config files from other packages as well.

**Comment by karnash** [comment]
![image](https://cloud.githubusercontent.com/assets/5040782/23215611/675c682c-f8e9-11e6-82ae-fe7dfdd38cbd.png)

**Comment by karnash** [comment]
my app.config
![image](https://cloud.githubusercontent.com/assets/5040782/23215996/bdbef224-f8ea-11e6-9abd-b34bb47e2aed.png)

![image](https://cloud.githubusercontent.com/assets/5040782/23216009/cfbf0e14-f8ea-11e6-84be-bfd34adc59a7.png)

sending the mail
![image](https://cloud.githubusercontent.com/assets/5040782/23216054/fb7ceb20-f8ea-11e6-81c8-866a1bbc3999.png)

![image](https://cloud.githubusercontent.com/assets/5040782/23216089/1968db76-f8eb-11e6-9e9f-1127e9523a62.png)

**Comment by karnash** [comment]
mmmmmmmm... works when i inyect the dependecy like that
![image](https://cloud.githubusercontent.com/assets/5040782/23216408/3fdd4354-f8ec-11e6-9178-c2cf03252335.png)

**Comment by karnash** [comment]
but if i wanna implement in another file a php class how i can inyect ?

**Comment by Bogardo** [comment]
Use the Mailgun facade, not the \Mailgun\Mailgun class.

```php
\Mailgun::raw('Hello World', function($msg){
    $msg->to('mymail@gmail.com');
});
```

**Comment by karnash** [comment]
thk. a lot chief..!!, master..!!!  now time to work with our package, and the inline css ..... thk greate job..!!!
