### ISSUE TITLE
Store mails

### ISSUE THREAD

**Issue by qrczak** [Bogardo/Mailgun#105]
Is it possible to get all stored (temporary mailbox for incoming) emails?

**Comment by Bogardo** [comment]
This package does not support fetching stored email out of the box.
What you can do is access the underlying Mailgun Api with the `Mailgun::api()` method.
(See the section about Mailing lists in the Readme: https://github.com/Bogardo/Mailgun#mailing-lists for an example)

Please refer to the Mailgun documentation regarding stored messages: https://documentation.mailgun.com/api-sending.html#retrieving-stored-messages
