### ISSUE TITLE
dependency issue

### ISSUE THREAD

**Issue by gaurav16694** [Bogardo/Mailgun#107]
I am getting the following error:

```
FatalThrowableError in AppServiceProvider.php line 38:
Parse error: syntax error, unexpected 'createWithConfig' (T_STRING), expecting variable (T_VARIABLE) or '$'
```

**Comment by Bogardo** [comment]
Could you please post the content of your `AppServiceProvider.php` file?

**Comment by dustingraham** [comment]
@Bogardo the error message above is generated by the problem here: https://github.com/Bogardo/Mailgun/commit/ff05ca54993642443563d4242413064db03d64af
