### ISSUE TITLE
Change email domain?

### ISSUE THREAD

**Issue by dambridge** [Bogardo/Mailgun#109]
I'm looking to provision several domains on Mailgun through my app. At this time, I see that the Mail sender takes the domain setting from the Config only. Any plans to make this a setting that can be passed in? If not, has anyone else looked at doing this yet?

**Comment by Bogardo** [comment]
The domain is fetched from the config [in the `send()` method](https://github.com/Bogardo/Mailgun/blob/a9f3cfce7fbae124bde43547dcaefb8d3e72a0f5/src/Mail/Mailer.php#L67).
You should be able to set the config value dynamically just before sending.

**Comment by dambridge** [comment]
Wasn't sure if I could actually do that or not. Will give it a shot and report back if you like.

**Comment by dambridge** [comment]
Yep, works a treat! Just have something like
```
config(['mailgun.domain' => $campaign->domain]);

Mailgun::send(...
```

**Comment by csimpi** [comment]
Thank you for this lib, it's awesome!
Mailgun is mostly about sending emails from different domains, I'd request a feature.
I think there should be a 
`$message->domain('mycustomdomain.com');`
method to change the domain on the fly. Changing the domain in the configuration file a bit hacky feeling, I'm not completely comfortable with this.
Thank you 🙏
