### ISSUE TITLE
Support for recipient variables when batch-sending

### ISSUE THREAD

**Issue by kJamesy** [Bogardo/Mailgun#11]
From the manual: http://documentation.mailgun.com/user_manual.html#batch-sending when batch-sending, Mailgun only knows to send emails to individual recipients (i.e. one recipient in the 'to' field) when you use recipient variables. Batch sending has an advantage over using the Mailgun::send in a loop since there's only one API call with the former therefore less loading time for the user. And then there's the advantage of using the same to personalise the emails.
Could you kindly add this feature?

Great work!

**Comment by azamat-sharapov** [comment]
I can't get this work. Has anybody used this feature? I tried both ways like described above, but variables don't get replaced in message body.

**Comment by azamat-sharapov** [comment]
Okay, **important** note to anyone who can't get this work: Make sure you are not using `catch_all` config option!
