### ISSUE TITLE
Sensitive values are kept in config

### ISSUE THREAD

**Issue by bul-ikana** [Bogardo/Mailgun#110]
Sensitive values like mailgun private API key are kept in config file, where they can be commited to source control and be mistakenly distributed. 

From Laravel 5 onwards, you can set this values in `.env` files. 

Mailgun config values should be loaded from .env files so they are not distributed by mistake. This has the added benefit than different values can be set for different environments without editing the config file.

**Comment by Bogardo** [comment]
I don't think this package needs to be responsible for that.
You can just as easily do the following right?

```php
// config/mailgun.php
'domain' => env('MAILGUN_DOMAIN')
'api_key' => env('MAILGUN_API_KEY')
```

```ini
# .env

MAILGUN_DOMAIN=example.com
MAILGUN_API_KEY=123456789abcdefg
```

**Comment by bul-ikana** [comment]
That is exactly what I did in #111 

Of course you can always do it, but I think it would be helpful to have it as default. This helps newcomers to avoid silly mistakes and immediately follows laravel best practices.

**Comment by dustingraham** [comment]
The PR looks helpful.

**Comment by matijakovacevic** [comment]
any info when will it be merged?
