### ISSUE TITLE
AppServiceProvider error

### ISSUE THREAD

**Issue by kuzne4ik537** [Bogardo/Mailgun#112]
When I try to add this code:
$this->app->bind('mailgun.client', function() {
            return new  \Http\Adapter\Guzzle6\Client::createWithConfig([
                'headers' => [
                    'Content-Type' => 'application/x-www-form-urlencoded'
                ]
            ]);
        });
 to AppServiceProvider.php register. I have this exception 
FatalThrowableError in AppServiceProvider.php line 27:
Parse error: syntax error, unexpected 'createWithConfig' (T_STRING), expecting variable (T_VARIABLE) or '$'
And Phpstorm also underline with red color this semicolon  :  \Http\Adapter\Guzzle6\Client::createWithConfig

**Comment by Bogardo** [comment]
It probably works if you drop the `new` keyword.

```php
$this->app->bind('mailgun.client', function() {
    return \Http\Adapter\Guzzle6\Client::createWithConfig([
        'headers' => [
            'Content-Type' => 'application/x-www-form-urlencoded'
        ]
    ]);
});
```

That seems to be an error in the docs, I'll update that.
