### ISSUE TITLE
HTTP Client Dependency error

### ISSUE THREAD

**Issue by timgithinji** [Bogardo/Mailgun#113]
Maybe I'm missing something obvious but I can't seem to figure this out.

When I try adding this code

```php
$this->app->bind('mailgun.client', function() {
    return new \Http\Adapter\Guzzle6\Client::createWithConfig([
        // your Guzzle6 configuration
    ]);
});
``` 

to the `MailgunServiceProvider register()` method I get a syntax error `Unexpected createWithConfig, expecting variable`

Please help.

**Comment by Bogardo** [comment]
It probably works if you drop the `new` keyword.

```php
$this->app->bind('mailgun.client', function() {
    return \Http\Adapter\Guzzle6\Client::createWithConfig([
        'headers' => [
            'Content-Type' => 'application/x-www-form-urlencoded'
        ]
    ]);
});
```

That seems to be an error in the docs, I'll update that.
