### ISSUE TITLE
Unable to parse URI: https://///messages

### ISSUE THREAD

**Issue by iulianba** [Bogardo/Mailgun#115]
Hello,

I think I did something wrong when I tried to implement Guzzle 6 example. Before this step, I was always getting **class mailgun.client does not exist**

So I added in register of AppServiceProvider:

```php
$this->app->bind('mailgun.client', function() {
    return \Http\Adapter\Guzzle6\Client::createWithConfig([
    
    ]);
});
```

Do i need to actually write a config in there? I have no idea what should I do.

Thanks

**Comment by Dartanjan** [comment]
I'm having the sam issue. Upgraded to v5, got `class mailgun.client does not exist`, installed Guzzle6 adapter, bound to container (with no config) and now I'm seeing this error message. I assume I need to add a base url or something, but it would be useful if there was an upgrade guide when new versions have breaking changes.

**Comment by iulianba** [comment]
I fixed the issue by generating the config file. In older version this was not a requirement, from what I knew:

`php artisan vendor:publish --provider="Bogardo\Mailgun\MailgunServiceProvider" --tag="config"`

Configure api settings and you should be good to go.

**Comment by Dartanjan** [comment]
Thanks! One question – setting has a `public_api_key`. Not sure what that is, Mailgun only gives private key, domain, smtp user/pass.

**Comment by iulianba** [comment]
I added the private key to both public_api_key and api_key. Not sure if it`s the smart/right way of doing it.

**Comment by Bogardo** [comment]
You can find your public API key in your account under 'Security'.
https://app.mailgun.com/app/account/security

The key should start with `pubkey-`

**Comment by iulianba** [comment]
I have the same key under the link you provided and domain settings. And starts with: key-xxxx

Is it safe to add it for public_api_key and api_key?

Thanks

**Comment by dimasx010** [comment]
in laravel v 5.7 need install

` composer require php-http/guzzle6-adapter ^1.0`

add in providers

```
$this->app->bind('mailgun.client', function() {
    return \Http\Adapter\Guzzle6\Client::createWithConfig([
    
    ]);
});
```
And finally

`php artisan vendor:publish --provider="Bogardo\Mailgun\MailgunServiceProvider" --tag="config"`

Gracias Totales
