### ISSUE TITLE
Class 'Mailgun' not found

### ISSUE THREAD

**Issue by stefanmahr** [Bogardo/Mailgun#117]
Hello!

I have following problem:

If I would like to use Mailgun::send.... I get the following error:

> FatalThrowableError Class 'Mailgun' not found

I have quit installed everthing correct... in my app.php I have added the provider and the alias...

I am using Laravel 5.4

Can everybody help me?

**Comment by mounssif** [comment]
Add this in your controller below namespace:

use Mailgun;
