### ISSUE TITLE
Trying to get property of non-object in Response.php (line 37)

### ISSUE THREAD

**Issue by kirandg7709** [Bogardo/Mailgun#127]
$resopnse = Mailgun::raw("This is the email body", function ($message) {
                        $message
                            ->subject('Your Invoice')
                            ->to('test@gmail.com', 'Test User')
                            ->trackOpens(true)
                            ->campaign(<campaign_id>);
                    });
                  
        print_r($resopnse);exit;

This is my code to send mail using Mailgun using laravel.But i'm getting the following error,
Trying to get property of non-object in Response.php (line 37).Please resolve this issue asap.

**Comment by abbatis** [comment]
Please read this part of the documentation https://github.com/Bogardo/Mailgun#guzzle-6-example-implementation
