### ISSUE TITLE
Documentation does not contain information about how to configure Mailgun Account

### ISSUE THREAD

**Issue by pareekbhagu** [Bogardo/Mailgun#130]
With Laravel's built in Mailgun, I can send email. but can't receive emails with using this repo. ( Though composer  successfully installed it, only problem is that mail does not reach the inbox, I get a 200 Response, with http_response_header as "Mailgun Magnificent API");

Only reason could be that Mailgun can't find correct API key and domain parameters.
It would be better if the guide contains on how to do it. 
For my specific errors, I shall add details later.

**Comment by abbatis** [comment]
Please check if your configuration is set-up according to documentation. Make sure your API-keys, domain and from-address are set-up.

Configuring your Mailgun account is out of scope for this project.
