### ISSUE TITLE
Batch Sending and Passing in Email Addresses

### ISSUE THREAD

**Issue by dukesnuz** [Bogardo/Mailgun#135]
What I am confused about is when using Batch Sending, How does each email address get passed in tot he closure. Also what if there is more than one data set needed in the email blade? How would this get passed in? 

See this issue [Batch Sending Mail Issue #50](https://github.com/Bogardo/Mailgun/issues/50)

Thank you

**Comment by connecteev** [comment]
@dukesnuz did you figure this out?

I am trying to figure out how to pass $users into Mailgun::send() and the closure
```
Route::get('/mail', function () {
	$data = [
		'name' => 'name one',
		'age' => 55,
		'city' => 'portland',
		'customer' => 'Kevin P',
		'url' => 'http://laravel.com'
	];

	$users = [
		'email1@gmail.com' => [
			'name' => 'Person One',
			'age' => 37,
			'city' => 'New York',
			'url' => 'http://laravel.com'
		],
		'email2@gmail.com' => [
			'name' => 'Person Two',
			'age' => 40,
			'city' => 'SF',
			'url' => 'http://url2.com'
		],
	];

	Mailgun::send('emails.mailgun_test', $data, function($message) {
		foreach ($users as $email => $userData) {
			$message->to($email)->subject('Welcome, ' . $email);
		}

	});

});

```

I keep hitting a wall with:
```
ErrorException (E_NOTICE)
Undefined variable: users
```

**Comment by connecteev** [comment]
@Bogardo stuck on this and would really appreciate an example here on how to batch send to 1000 emails with one API call, while passing an array of 1000 data points into the email template.

**Comment by cosmini** [comment]
You have to mention that your local variable is being used by the anonymous function with `use`

```
Mailgun::send('emails.mailgun_test', $data, function($message) use ($users) {
		foreach ($users as $email => $userData) {
			$message->to($email)->subject('Welcome, ' . $email);
		}

	});
```

But this approach is not sending batch! This sending same email to 1000 recipients.

**Comment by Bogardo** [comment]
> @Bogardo stuck on this and would really appreciate an example here on how to batch send to 1000 emails with one API call, while passing an array of 1000 data points into the email template.

Have you tried using recipient variables?

https://github.com/Bogardo/Mailgun/issues/50#issuecomment-127639254
