### ISSUE TITLE
[curl] 60: SSL certificate problem: unable to get local issuer certificate [url] https://api.mailgun.net/v2/myDomain/messages

### ISSUE THREAD

**Issue by Dimidel** [Bogardo/Mailgun#136]
Hello, 
Since 1 or 2 days, i'm encountering this error on an old Laravel 4.x : 
**[curl] 60: SSL certificate problem: unable to get local issuer certificate [url] https://api.mailgun.net/v2/myDomain/messages**
Please can you help me ?
Thank you !

**Comment by jhalak** [comment]
I am having the same issue here for last 2/3 days.

**Comment by jhalak** [comment]
Hey @Dimidel, I have found a solution that works for me. I have replaced the `cacert.pem` file located in `vendor/guzzle/guzzle/src/Guzzle/Http/Resources/` directory with the new one downloaded from here `https://curl.haxx.se/ca/cacert.pem`.

`cd vendor/guzzle/guzzle/src/Guzzle/Http/Resources/`
`mv cacert.pem cacert.pem.old` `//-> just as a backup`
`wget https://curl.haxx.se/ca/cacert.pem`

That works for me.

**Comment by Dimidel** [comment]
Thank you @jhalak. I will try your solution.
