### ISSUE TITLE
Switching endpoint

### ISSUE THREAD

**Issue by Sinnbeck** [Bogardo/Mailgun#150]
Currently mailgun does not support email validation on the eu api endpoint (and don't plan to).
Is there any plans of allowing switching endpoint for validation purposes? It would seem that this is a needed feature for all eu users.

**Comment by johannesschobel** [comment]
did you manage to solve this issue @Resin01 ? I am currently in the same position - need to switch from `US` to `EU`. Any success so far?
All the best

**Comment by johannesschobel** [comment]
ok @Resin01 , i figured it out.. you can simply change the `api.endpoint` parameter in the `mailgun.php` config file! Thats basically all you need to do..
Change it from `api.mailgun.com` to `api.eu.mailgun.com` and you're ready to go!
