### ISSUE TITLE
Question on Mailgun Endpoint URL

### ISSUE THREAD

**Issue by ridvanbaluyos** [Bogardo/Mailgun#20]
Hi,

First of all, thank you for this awesome package. Very easy to use!

However, I have a question. On my local machine, the sending of email works perfectly fine. However when I deployed it to my test server, I keep getting the ff. error:

Mailgun \ Connection \ Exceptions \ MissingEndpoint
The endpoint you've tried to access does not exist. Check your URL.

Is there anything that I miss or I have to configure when deploying?

Thanks,
Ridvan

**Comment by nu1ww** [comment]
I've same issue. app develop using laravel 4.2, this package installed correctly. I'm working on local environment plan to send emails via mailgun API 
```
Mailgun \ Connection \ Exceptions \ MissingEndpoint 
The endpoint you've tried to access does not exist. Check your URL. 
```

Domain and API set in services.php  
 
```
'mailgun' => array(
		'domain' => 'sandboxe786b43f2c3447fdaf02258fae929ab8.mailgun.org',
		'secret' => 'xxxxxx2833725df29b4ad6bbaadc1d9',)
```
can you help me to to sort it out ?
