### ISSUE TITLE
Wrong message id for email header causing emails to go straight to spam in some servers

### ISSUE THREAD

**Issue by ayyobro** [Bogardo/Mailgun#41]
Some emails that I send keep getting put into the spam folders of some email servers. 
I poured through your docs to maybe pinpoint the issue, but could not.

I contacted Mailgun support to maybe shed some light on the issue, and they said it could be that my 'message-id' in my email header is wrong since it shows 'Message-Id: <282dc62aa198e497a5358f0aeeff56da@localhost>. He mentioned that it should, in reality, be the same as the 'From:' address in the email.

Maybe this is a bug on your end? If not, please let me know common causes of this issue, if you have knowledge of them.

**Comment by Bogardo** [comment]
Hi,
Could you please post a snippet of your code so I can try to reproduce it.

**Comment by ayyobro** [comment]
Hey, 

Figured out the problem. 

While configuring mailgun I set 'secret' to the mailgun password as opposed to the actual secret api key. 

This is what seemed to be causing the issue since, after I changed it to the secret api key, it all works now and no mail goes to spam on my users mail servers.

Excuse my ignorance and thanks for your great package!

**Comment by Bogardo** [comment]
@ayyobro Glad you solved your issue.
