### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by lightwalkernet** [Bogardo/Mailgun#42]
I realize laravel 5 is not yet released but we are getting very close. Would be really great to have the Mailgun package working with laravel 5 when it's released. Your package is such a great package. Many thanks for all you work. It's been a life saver.

**Comment by BCleverly** [comment]
+1, Need the functionality for a project being worked on at the moment.

**Comment by Bogardo** [comment]
I'm definitely planning on making this package compatible with Laravel 5 but unfortunately I haven't found the time to do it yet.
Note that Laravel 5 now has better [support for Mailgun](http://laravel.com/docs/5.0/mail) out of the box, though still limited to only send emails (without tags, campaigns etc.)

**Comment by ddewit** [comment]
+1

**Comment by theblindfrog** [comment]
+1

**Comment by ellisthedev** [comment]
Any update on this progress? Really need the `o:tag` support for a project we're working on and it drives me nuts this isn't supported by default.

**Comment by EHLOVader** [comment]
+1

**Comment by ritey** [comment]
I've made a start, a pull request has been submitted...

**Comment by ritey** [comment]
Any update on this?

**Comment by Kryptonit3** [comment]
Does the built in mail provider in L5 not work? There is support for mailgun.

**Comment by ddewit** [comment]
The built in support is pretty basic and though you can do a lot with adding headers to a mailgun mail, you cannot easily manage lists and subscribers and so forth. At least, not that I'm aware of.

**Comment by jjosephs** [comment]
+1

**Comment by jarbitlira** [comment]
## I added support to L5, see the [PR](https://github.com/Bogardo/Mailgun/pull/52).
While the PR is in review. you can use my repo following the next instruction:
* Add the repository url and set minimum-stability in your composer.json file
``` json
"repositories": [
  {
  "type": "git",
  "url": "https://github.com/jarbitlira/Mailgun.git"
  }
],
"config": {
  "minimum-stability":"dev"
}
```
*  Add the next dependency
```
"bogardo/mailgun": "dev-laravel5"
```
* Run composer update from the command line
``` bash
 composer update --prefer-source
```
* Finally see the [README.md](https://github.com/jarbitlira/Mailgun/blob/laravel5/README.md) for configure in laravel 5

#### If some problem is detected. You can make an issue or a PR on my repo.

Regards and luck.
