### ISSUE TITLE
Bogardo/Mailgun and Password Reminders - Class 'Bogardo\Mailgun\MailgunApi' not found

### ISSUE THREAD

**Issue by GodsBest** [Bogardo/Mailgun#43]
I have used this package several times on a number of projects but this is the first time I am using with Password Reminders. 

I followed the instructions given here: http://bogardo.com/mailgun-and-password-reminders/. I had issues with creating a namespace for the two new files but I had that resolved by using the autoload section of `composer.json`. Now, when I load the reminder form supply my e-mail address and submit (posts to password/reset), I get the following error and I do not get the password reset e-mail:

`Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_ERROR) 
Class 'Bogardo\Mailgun\MailgunApi' not found
Open: ....../vendor/bogardo/mailgun/src/Bogardo/Mailgun/Mailgun.php`

In the vendor folder, I can see the MailgunApi class here: Bogardo\Mailgun\Mailgun\MailgunApi. How do I resolve this issue? Let me know if you need more information.

I am using Laravel 4.2

**Comment by Bogardo** [comment]
@GodsBest Have you managed to resolve this issue yet? If you haven't please let me know and I'll take a look at it. Sorry for the delay.

**Comment by GodsBest** [comment]
@Bogardo,  thanks for getting back to me. No this is not solved yet. I decided to uninstall the package so at least I can continue with the other aspects of my project.

**Comment by Bogardo** [comment]
@GodsBest I'll try to implement the password reminders myself in the coming days to see if I stumble upon the same issue.

**Comment by GodsBest** [comment]
@Bogardo I'll be looking forward to your findings and whatever solution you may come up with. Thank you.

**Comment by Bogardo** [comment]
@GodsBest I've just setup a clean Laravel 4.2 installation with just the this package and I followed my own tutorial to setup the reminders and it seems to work fine.
Could you please provide me the contents of your composer.json.

**Comment by GodsBest** [comment]
@Bogardo the contents of my composer.json are as below:

`{
        "name": "laravel/laravel",
        "description": "The Laravel Framework.",
        "keywords": ["framework", "laravel"],
        "license": "MIT",
        "type": "project",
        "require": {
                "laravel/framework": "4.2.*",
                "guzzlehttp/guzzle": "~4.0",
                "intervention/image": "~2.1",
                "intervention/imagecache": "~2.1",
                "jenssegers/oauth": "~1.1",
                "bogardo/mailgun": "3.1.*"
        },
        "autoload": {
                "classmap": [
                        "app/commands",
                        "app/controllers",
                        "app/models",
                        "app/database/migrations",
                        "app/database/seeds",
                        "app/tests/TestCase.php"
                ],
                "psr-4": {
                        "Nuru\\": "src/Nuru/"
                }
        },
        "scripts": {
                "post-install-cmd": [
                        "php artisan clear-compiled",
                        "php artisan optimize"
                ],
                "post-update-cmd": [
                        "php artisan clear-compiled",
                        "php artisan optimize"
                ],
                "post-create-project-cmd": [
                        "php artisan key:generate"
                ]
        },
        "config": {
                "preferred-install": "dist"
        },
        "minimum-stability": "stable"
}`

**Comment by Bogardo** [comment]
Seems ok to me. Hop on over to https://gitter.im/Bogardo/Mailgun if you can.

**Comment by Bogardo** [comment]
@GodsBest What's the status on this?

**Comment by GodsBest** [comment]
@Bogardo Release 3.1.6 does indeed fix the issue. Thank you very much.

**Comment by Yokeshthebouncer** [comment]
Is that the above issue fixed in laravel5.1? Im getting Failed opening required.
