### ISSUE TITLE
Batch Sending Mail Issue

### ISSUE THREAD

**Issue by venkatiiitb** [Bogardo/Mailgun#50]
Hi Bogardo,

I am trying to send a batch mail to multiple recipients at the same time using below code using Laravel framework.

Mailgun::send('emails.mudrush', $data, function($message) use($users)
		{					
			$message->subject('Last day to WIN free passes to The Mud Rush' );
		
			$message->to($users);

		});

If you see $users array has all the emails of the users. Now the issue is every user is able to see all the other users emails.

But we don't want to visible all the users emails.

**Comment by Bogardo** [comment]
The best way to fix this is by using recipient variables.
From the Mailgun Documentation:

>#### Batch Sending
>Mailgun supports the ability send to a group of recipients through a single API call.
>
>This is achieved by either:
> - Using Batch Sending by specifying multiple recipient email addresses as to parameters and using Recipient Variables.
> - Using Mailing Lists with Template Variables.

>>**Warning It is important when using Batch Sending to also use Recipient Variables. This tells Mailgun to send each recipient an individual email with only their email in the to field. If they are not used, all recipients’ email addresses will show up in the to field for each recipient.**

Take special note of the last (bold) paragraph.

Example:
```php
Mailgun::send(emails.mudrush', $data, function($message)
{
    $message->to([
        'user1@example.com',
        'user2@example.com',
        'user3@example.com',
    ]);
    $message->recipientVariables([
        'user1@example.com' => ['name' => 'John Doe'],
        'user2@example.com' => ['name' => 'Foo Bar'],
        'user3@example.com' => ['name' => 'Baz Bar'],
    ]);
});
```

Another option would probably be to use the bcc() method but I recommend using the recipient variables.

```php
Mailgun::send('emails.mudrush', $data, function($message) use($users)
{
	$message->subject('Last day to WIN free passes to The Mud Rush');
	$message->bcc($users);
});
```

## Simmilar issues:

[Issue using To foreach loop #31](https://github.com/Bogardo/Mailgun/issues/31)
[Support for recipient variables #34](https://github.com/Bogardo/Mailgun/issues/34)

**Comment by dustingraham** [comment]
Thanks @Bogardo I didn't see $message->recipientVariables in the documentation so I was also wondering. I see it in the code now.

Might consider returning $this so we can chain functions.

**Comment by dukesnuz** [comment]
I am trying to accomplish same as @dustingraham . I want to use ```recipientVariables```
My question is:
If all email addresses are in and array, How do I pass them into here?
```$message->to([
        'user1@example.com',
        'user2@example.com',
        'user3@example.com',
    ]);
    $message->recipientVariables([
        'user1@example.com' => ['name' => 'John Doe'],
        'user2@example.com' => ['name' => 'Foo Bar'],
        'user3@example.com' => ['name' => 'Baz Bar'],
    ]);


Say I have something like this:
$e = array_chunk($emails, $size);

Mailgun::send(emails.mudrush', $data, function($message)
{
    $message->to([
      (How would I pass the email addresses in here?)
        'user1@example.com', 
        'user2@example.com',
        'user3@example.com',
    ]);
    $message->recipientVariables([
     (How would I pass the recipient variables in here?)
        'user1@example.com' => ['name' => 'John Doe'],
        'user2@example.com' => ['name' => 'Foo Bar'],
        'user3@example.com' => ['name' => 'Baz Bar'],
    ]);
});```

I have been trying to figure this out for a long time.
Thank you very much.
