### ISSUE TITLE
Mailgun::lists()->addMember not working in production

### ISSUE THREAD

**Issue by mocheaz** [Bogardo/Mailgun#51]
For some reason i am able to add a member to a list in my dev environment, but it's not working in my production.

Mailgun::send() is working fine.

Any idea why?

**Comment by Bogardo** [comment]
Are any/other Mailinglist methods working on your production environment?

**Comment by mocheaz** [comment]
I just tested Mailgun::lists()->get() and Mailgun::lists()->all() and it worked fine.

**Comment by mocheaz** [comment]
Any updates?

**Comment by jarbitlira** [comment]
Hi @mocheaz.
Check the logs generated by laravel, this can say you what's the possible problem.

**Comment by Bogardo** [comment]
@mocheaz Have you managed to resolve this issue?
