### ISSUE TITLE
Method Mail::raw() not supported

### ISSUE THREAD

**Issue by leonardo-ferreira-caldas** [Bogardo/Mailgun#54]
Because Mail::raw() is not supported, it is mandatory that a view is passed, but in cases where you rendered the view before to execute some parsing function, like using CSSInline class, you cant just pass the parsed data to Mailgun::send.

**Comment by ddewit** [comment]
This has been an issue for quite some time. As a quick 'work-around', you can create an empty view where you can pass 1 variable (containing the previously rendered view as an HTML string) to and immediately display it, as the only thing the view does...

It's not perfect, but it's a quick and workable solution.

**Comment by Bogardo** [comment]
I'll see if I can add a `Mailgun::raw()` feature this week.

**Comment by Gadurp1** [comment]
Any chance you'll be adding this feature soon?

**Comment by nickbr5** [comment]
Any news on this? I also need this function.

**Comment by Dartanjan** [comment]
+1

**Comment by Bogardo** [comment]
Please update to the lastest release and review the installation instructions.
