### ISSUE TITLE
can't use guzzlehttp 6.x,please update dependecy

### ISSUE THREAD

**Issue by argb** [Bogardo/Mailgun#55]
Please update,i am using guzzlehttp 6.x

**Comment by Bogardo** [comment]
Guzzle is a dependency for the mailgun-php library, on which this package relies. I see you've already created an issue on their project (https://github.com/mailgun/mailgun-php/issues/97).

**Comment by argb** [comment]
@Bogardo yes,I created 2 issue for both of you :D
