### ISSUE TITLE
Compatible in Laravel 5.2?

### ISSUE THREAD

**Issue by guilhermegonzaga** [Bogardo/Mailgun#59]
I wonder if this package is compatible with Laravel 5.2?

**Comment by MehmetNuri** [comment]
Is not  it not runing on Laravel 5.2 ?

**Comment by avnir** [comment]
This is still not working on Laravel 5.2 

Fatal error: Call to undefined method Mailgun\Mailgun::send()
Fatal error: Call to undefined method Mailgun\Mailgun::later()

**Comment by bikedel** [comment]
any answer to wether it is 5.2 compatible?

**Comment by mcblum** [comment]
I have the same issue :(

**Comment by Dartanjan** [comment]
Same issue, the package is **not** 5.2 compatible. 
Is this still under development? Too bad if it’s not, there are no easy replacements.

**Comment by mcblum** [comment]
I totally forgot about this issue thread. I wish I remembered how I fixed this but all of our apps are running 5.2+ and they all work with this package. For the life of me I can't remember what I did, but I know it does, in fact, work.

**Comment by Dartanjan** [comment]
Actually, the issue I'm having is using this package for password resets. This no longer applies to 5.2+ http://bogardo.com/mailgun-and-password-reminders/ So that needs a heavy update.

**Comment by FilipQL** [comment]
So, this  package is not 5.2 compatible? Also, I see that it uses _mailgun/mailgun-php_ **v1.8**, but the current stable version is _mailgun/mailgun-php_ **v2.1.2**, and if you have already installed the latest version of guzzlehttp/guzzle (**6.2.1**) - this package will not work...

**Comment by afinayor** [comment]
I have the same issue. A update is needed Asap. Av tried using the normal Mailgun raw api library. Not working with laravel 5.2. I keep getting error. Or guys anyone with a workaround.

**Comment by Bogardo** [comment]
Please update to the lastest release and review the [installation instructions](https://github.com/Bogardo/Mailgun#installation).
