### ISSUE TITLE
Guzzle Dependency issues

### ISSUE THREAD

**Issue by thorakmedichi** [Bogardo/Mailgun#60]
It appears the bogardo/mailgun 4.0.* for Laravel 5 package has a conflict with one of my other packages.

My other package requires guzzlehttp/guzzle 6.1.1 but when I try to add this package I get a composer error:

- Conclusion: don't install guzzlehttp/guzzle 6.1.x-dev
- Conclusion: don't install guzzlehttp/guzzle 6.1.1
- mailgun/mailgun-php v1.8 requires guzzlehttp/guzzle ~5.0 -> satisfiable by guzzlehttp/guzzle[5.3.x-dev].
- Can only install one of: guzzlehttp/guzzle[6.1.0, 5.3.x-dev].

Can this be changed so your package has a MINIMUM requirement for guzzle 5.0. Having a newer version of Guzzle should not inhibit the installation of this package.

**Comment by Bogardo** [comment]
Guzzle dependencies are set in the [mailgun-php](https://github.com/mailgun/mailgun-php/blob/master/composer.json#L5) package, not in this package.
