### ISSUE TITLE
SSL Certificate problem

### ISSUE THREAD

**Issue by HekmatFavid** [Bogardo/Mailgun#62]
By sending mail following error show:

RequestException in RequestException.php line 51: cURL error 60: SSL certificate problem: unable to get local issuer certificate

How to solve it?

**Comment by Bogardo** [comment]
I don't think this is an issue with this package. Please post some more information about your issue.

**Comment by gilbertovb** [comment]
I had the same issue with the test script:
# Include the Autoloader (see "Libraries" for install instructions)
require 'vendor/autoload.php';
use Mailgun\Mailgun;

# Instantiate the client.
$mgClient = new Mailgun('my api key');
$domain = "my domain";

# Make the call to the client.
$result = $mgClient->sendMessage($domain, array(
    'from'    => 'Excited User <postmaster@my domain>',
    'to'      => 'Baz <nono@mail.com>',
    'subject' => 'Hello',
    'text'    => 'Testing some Mailgun awesomness!'
));

**Comment by testwts** [comment]
Bogardo, I'm facing same issue emails send code gives me this error

cURL error 60: SSL certificate problem: unable to get local issuer certificate

What should I do to solve this error?

**Comment by developingo** [comment]
Same problem here, working on Windows Server 2012 standard, laravel 5.1.36

some people suggest this could be caused by guzzlehttp/guzzle 5.0

I have ohter two laravel installations (4.1 and 4.2) with mailgun 2.* and 3.0.* working well in the same server so this should be related with this version of mailgun or its dependencies

**Comment by raunak-cispl** [comment]
I too facing the same issue, but i don't have guzzlehttp/guzzle.

My code is

```
$data = [
                'profile_name' => $user->first_name . ' ' . $user->last_name,
                'email_id' => $user->email,
                'reset_link' => $reset_link
            ];

            Mailgun::send(array('email.forgotten_password'), $data, function($message) use ($user) {
                $message->to($user->email, $user->first_name . ' ' . $user->last_name)->subject('Account Recovery - ' . SITE_NAME);
            });
```

Laravel version: 5.1
bogardo/mailgun:: "4.0.*

Any help would be greatly appreciated, thanks.

**Comment by Bogardo** [comment]
The Guzzle dependency has been removed in the latest release.
Please update review the [installation instructions](https://github.com/Bogardo/Mailgun#installation) on how to configure your client.
