### ISSUE TITLE
Attachments appearing inline

### ISSUE THREAD

**Issue by devdurbs** [Bogardo/Mailgun#67]
Attaching files to the email works . . . but the attachment also appears inline in the email.
This is the code used:
`$message->attach(data['path'], $data['name']);`
How to prevent it appearing inline?

**Comment by Bogardo** [comment]
Hi @devdurbs,

I've tried to reproduce this issue but attachments do not appear inline for me.
Are you sure this is not your email client showing previews/thumbnails of your attachments?
I know Gmail does this and probably some other email clients.

**Comment by devdurbs** [comment]
Could well be. I'll get some colleagues to test with their email clients.
