### ISSUE TITLE
Laravel 5.1 support?

### ISSUE THREAD

**Issue by sixty8** [Bogardo/Mailgun#68]

**Comment by johannesschobel** [comment]
It works on L 5.1.. I use it in my current project!

**Comment by zurez** [comment]
- bogardo/mailgun 4.0.0 requires mailgun/mailgun-php ^1.8 -> satisfiable by mailgun/mailgun-php[v1.8] but these conflict with your requirements or minimum-stability.


I am getting this issue. On Larevel 5.1 any advice @johannesschobel

**Comment by johannesschobel** [comment]
My ```composer.json``` file in the root directory looks like this:

``` json
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "bogardo/mailgun": "4.0.*"
    },
   ... ,
   "config": {
        "preferred-install": "dist"
    }
   ...
```

Works like a charm..

What are you using?

**Comment by zurez** [comment]
I am using guzzle6 maybe thats why stuff have broken ?

**Comment by johannesschobel** [comment]
could be.. the "old" ```mailgun/mailgun-php``` package (this one here uses 1.8 - current version is 2.1) uses ```guzzle5``` per default..

Note, that ```mailgun/mailgun-php``` has removed ```guzzle6``` as dependency in their current implementation. However, you are free to use guzzle (see their readme file). However, if you are using this package you are _bound_ to ```guzzle5``` for now..

I do not know if this package is still maintained..

**Comment by Bogardo** [comment]
Please update to the lastest release and review the [installation instructions](https://github.com/Bogardo/Mailgun#installation).
