### ISSUE TITLE
Guzzle 6

### ISSUE THREAD

**Issue by milocosmopolitan** [Bogardo/Mailgun#69]
Hello I've been using this plug in without any issue. However, with my last update on my project where I'm using "guzzlehttp/guzzle:~6.1.1", "guzzlehttp/oauth-subscriber: dev-master" for Oauth. So now  composer wouldn't install the plug in due to dependency version.  So I wanted to ask you guys whether, you are planning to update your project any sooner, or any workaround.

**Comment by milocosmopolitan** [comment]
https://github.com/Bogardo/Mailgun/pull/70

**Comment by mcblum** [comment]
What's the status of this? Was this ever accepted so we could move to Guzzle 6?

**Comment by Bogardo** [comment]
Please update to the lastest release and review the [installation instructions](https://github.com/Bogardo/Mailgun#installation).

**Comment by mcblum** [comment]
Thank you for doing this @Bogardo! I was only using templates through Mailgun so I made my own helper in the meantime, but your package is way better. I appreciate your paying attention to these issues and resolving it.

**Comment by Bogardo** [comment]
@mcblum Thanks, I really appreciate that.
I haven't been very responsive in the last months, which I regret but I've just been way to busy.

**Comment by mcblum** [comment]
@Bogardo such is life! I use this package in every project we have so I was very excited to see this come through. Thank you for contributing to the open source community.
