### ISSUE TITLE
Failed to install bogardo/mailgun, version 4.0.0

### ISSUE THREAD

**Issue by FilipQL** [Bogardo/Mailgun#73]
Hi,

I am using Laravel 5.2 with the latest version of guzzlehttp/guzzle [**6.2.1**]. When I try to install bogardo/mailgun, get the following error:

> C:\xampp\php\php.exe C:/xampp/htdocs/project-name/composer.phar require bogardo/mailgun:4.0.0 -n --no-progress
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - mailgun/mailgun-php v1.8 requires guzzlehttp/guzzle ~5.0 -> satisfiable by guzzlehttp/guzzle[5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.1.0, 5.2.0, 5.3.0, 5.3.1, 5.3.x-dev] but these conflict with your requirements or minimum-stability.
>     - bogardo/mailgun 4.0.0 requires mailgun/mailgun-php ^1.8 -> satisfiable by mailgun/mailgun-php[v1.8].
>     - Installation request for bogardo/mailgun 4.0.0 -> satisfiable by bogardo/mailgun[4.0.0].
> 
> Installation failed, reverting ./composer.json to its original content.

So, it seems that this package doesn't work with the latest version of guzzle... Can I expect this package to work with the latest version of guzzle any time soon, or I need to remove the current version and install 5.3.1?

**Comment by vafrcor** [comment]
I had same problem.
The newest `mailgun/mailgun:2.1.2` package doesn't need `guzzlehttp/guzzle:~5.0` anymore.
Hope this package will update dependency to newest mailgun package.

**Comment by zurez** [comment]
Same issue here.

**Comment by johannesschobel** [comment]
you need to install ```guzzle5.*```

**Comment by Bogardo** [comment]
Please update to the lastest release and review the [installation instructions](https://github.com/Bogardo/Mailgun#installation).
