### ISSUE TITLE
Non-static method Bogardo\Mailgun\Mailgun::lists() should not be called statically

### ISSUE THREAD

**Issue by giwrgos88** [Bogardo/Mailgun#74]
I'm using mailgun v4.\* on a laravel 5.2, and when I'm calling Mailgun::lists() I'm getting non-static method. here is my code same with the documentation

```
    if (!Mailgun::lists()->get($location['isoCode'] . '@test.com')) {
    }
```

any idea?

**Comment by Bogardo** [comment]
Support for laravel 5.1 and up has been added in the latest release. Though integrated support for Mailinglists have been dropped. Instructions for using the Mailinglist API [can be found in the Readme](https://github.com/Bogardo/Mailgun#mailing-lists).

Please update to the lastest release and review the [installation instructions](https://github.com/Bogardo/Mailgun#installation).
