### ISSUE TITLE
Send emails in batch and pass unique data per recipient

### ISSUE THREAD

**Issue by fakiolinho** [Bogardo/Mailgun#76]
I 've found in some closed old issues some mentions about `$m->recipientVariables();` but i cannot find anything in the docs and whatever i 've tried doesn't work. This is what i am trying:

```php
...
$m->to([
    'some@mail.com',
    'another@mail.com'
    ...
]);

$m->recipientVariables([
    'some@mail.com' => [
        'var1' => 'value1',
        'var2' => 'value2'
    ],
    'another@email.com' => [
        ...
    ]
]);
```

With the structure above `$var1` and `$var2` remain unknown in my template. Am i  missing sth here? Is `$m->recipientVariables([...]);` the only way to achieve sth like that here? If yes please consider adding this in your docs.

**Comment by Bogardo** [comment]
Hi @fakiolinho,
RecipientVariables are processed by Mailgun and not by Laravel/Blade.

See https://documentation.mailgun.com/user_manual.html#batch-sending

> To access a recipient variable within your email, simply reference %recipient.yourkey%. For example, consider the following JSON:
> 
> ```
> {
>   "user1@example.com" : {"unique_id": "ABC123456789"},
>   "user2@example.com" : {"unique_id": "ZXY987654321"}
> }
> ```
> 
> To reference the above variables within your email, use `%recipient.unique_id%`.

I hope this answers your question.
I'm currently working on the new version of the package and I'll make sure this will be covered in the documentation.

**Comment by fakiolinho** [comment]
Thanks @Bogardo that was fast. Yes that `%recipient.varName%` works perfect. Thanks.
