### ISSUE TITLE
Still maintained & Upgrade to Mailgun 2.1.*

### ISSUE THREAD

**Issue by johannesschobel** [Bogardo/Mailgun#77]
Hi @Bogardo and all other contributors,

first of all, thanks for this easy-to-use package!
I just wanted to ask, if this package is still maintained? Currently, Mailgun provides a 2.1.\* package for their own library. This one, however, still uses 1.8.\* 

Can you switch to 2.1.\* ?

Thanks a lot and keep up your work!
Cheers

**Comment by pouu69** [comment]
plz change

**Comment by johannesschobel** [comment]
pushing back to the top.. ;)

**Comment by mcblum** [comment]
Please!!! We really need Guzzle 6.

**Comment by Bogardo** [comment]
Please update to the lastest release and review the [installation instructions](https://github.com/Bogardo/Mailgun#installation).
