### ISSUE TITLE
Recipient Variables

### ISSUE THREAD

**Issue by kunxin-chor** [Bogardo/Mailgun#80]
Is there anyway to define recipient variables when doing batch sending?

**Comment by Bogardo** [comment]
Please take a look at:
[Batch Sending Mail Issue #50](https://github.com/Bogardo/Mailgun/issues/50)
[Issue using To foreach loop #31](https://github.com/Bogardo/Mailgun/issues/31)
[Support for recipient variables #34](https://github.com/Bogardo/Mailgun/issues/34)

Does that fix your issue?

**Comment by kunxin-chor** [comment]
Yes this does nicely. Was it in the docs, or did I miss it?
