### ISSUE TITLE
Call to undefined function Mailgun::isDeferred()

### ISSUE THREAD

**Issue by faisalwiz** [Bogardo/Mailgun#82]
Hi I am using laravel 5.2 and bogardo/mailgun": "4.0 
I execute the following code 
`
$responseed = Mailgun::send('general_template',array('mail_information'=>$temp_data) ,function ($emailOBJ){
            $emailOBJ->subject('test---teste--subject-qrq2r3q-'.mt_rand(56465498,9849849804908))->to('testemail@testdomain.com');
            $emailOBJ->tracking(true);
        });
`
it thrown following error
`FatalErrorException in ProviderRepository.php line 119:
Call to undefined method Bogardo\Mailgun\Facades\Mailgun::isDeferred()`

**Comment by Bogardo** [comment]
Please update to the lastest release and review the [installation instructions](https://github.com/Bogardo/Mailgun#installation).
