### ISSUE TITLE
Non-static method Bogardo\Mailgun\Mailgun::send() should not be called statically, assuming $this from incompatible context

### ISSUE THREAD

**Issue by faisalwiz** [Bogardo/Mailgun#84]
Hi I have installed  "bogardo/mailgun": "4.0.*" via composer and followed same steps defined in library
I am using following code to send email for testing but its thrown an error  
`Non-static method Bogardo\Mailgun\Mailgun::send() should not be called statically, assuming $this from incompatible context`
```php
Mailgun::send('front/emailtemplates/general_template',array('mail_information'=>$temp_data) ,function ($emailOBJ){
 $emailOBJ->subject('test---teste--subject-qrq2r3q-'.mt_rand(56465498,9849849804908))->to('emailaddress@gmail.com');
$emailOBJ->tracking(true);

});
```
 `vendor\bogardo\mailgun\src\Bogardo\Mailgun\Mailgun.php` file using using $this 

look the following function 
```php
 public function send($view, array $data, $callback, $mustInit = true)
    {
        if ($mustInit) {
            $this->_init();
        }
        $this->callMessageBuilder($callback, $this->message);
        $this->getMessage($view, $data);
        return $this->mailgun(true, config('mailgun.api_key'))->sendMessage(config('mailgun.domain'), $this->getMessageData(), $this->getAttachmentData());
    }
```
Any help will be appreciated I am using it because I need tracking of email

**Comment by Bogardo** [comment]
Please update to the lastest release and review the [installation instructions](https://github.com/Bogardo/Mailgun#installation).
