### ISSUE TITLE
Class mailgun.client does not exist in mailgun 5.0

### ISSUE THREAD

**Issue by raunak-gupta** [Bogardo/Mailgun#88]
Hi,

I have 2 Laravel application
_1st one is:_
Laravel version : 5.1.*
bogardo/mailgun: 4.0.*
_2nd one is:_ 
Laravel version : 5.2.*
bogardo/mailgun: ^5.0

1st one is working properly but in second application I'm getting an error

> ReflectionException in Container.php line 734: 
> Class mailgun.client does not exist

In my both the application I have same code which is.
```
use Mailgun;
--------
Mailgun::send('emails.common-body', $data, function ($message) use ($user) {
    $message
            ->subject($user['subject'])
            ->to($user['email'], $user['customer_first_name'] .' '. $user['customer_last_name'])
//            ->trackOpens(true)
            ->tag(['tag1']);
});
```

![2016-11-27_2103](https://cloud.githubusercontent.com/assets/22704179/20649389/009bbc70-b4e5-11e6-9fe9-d2697adf8009.png)

**Comment by Bogardo** [comment]
It looks like you forgot to register the HTTP Client.
Please check the [HTTP Client Dependency](https://github.com/Bogardo/Mailgun#http-client-dependency) section in the readme.

**Comment by raunak-gupta** [comment]
Ok, thanks but some how I was struggling to add the dependency of php-http/guzzle6-adapter in app.php file, so I downgraded to bogardo/mailgun: 4.0.* and it is working fine.

**Comment by connecteev** [comment]
Same. Issue's still happening.

OneStepAtATime:kb_skins kunalpunjabi$ composer require php-http/guzzle6-adapter
Using version ^2.0 for php-http/guzzle6-adapter
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install php-http/guzzle6-adapter v2.0.1
    - Conclusion: don't install php-http/guzzle6-adapter v2.0.0
    - Conclusion: remove php-http/httplug v1.1.0
    - Installation request for php-http/guzzle6-adapter ^2.0 -> satisfiable by php-http/guzzle6-adapter[2.x-dev, v2.0.0, v2.0.1].
    - Conclusion: don't install php-http/httplug v1.1.0
    - php-http/guzzle6-adapter 2.x-dev requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[2.0.x-dev, v2.0.0].
    - Can only install one of: php-http/httplug[2.0.x-dev, v1.1.0].
    - Can only install one of: php-http/httplug[v2.0.0, v1.1.0].
    - Installation request for php-http/httplug (locked at v1.1.0) -> satisfiable by php-http/httplug[v1.1.0].
Installation failed, reverting ./composer.json to its original content.
