### ISSUE TITLE
Readme correction: Mailgun::raw

### ISSUE THREAD

**Issue by jameskraus** [Bogardo/Mailgun#89]
The Readme file currently gives this as the example for Mailgun::raw:

`Mailgun::raw("This is the email body", $data, $callback);`

But the interface function does not accept a $data parameter:

```   
   /**
     * @param string   $message
     * @param \Closure $callback
     *
     * @return \Bogardo\Mailgun\Http\Response
     */
    public function raw($message, Closure $callback);
```

**Comment by jameskraus** [comment]
Pull request: https://github.com/Bogardo/Mailgun/pull/90

**Comment by Bogardo** [comment]
Thanks for noticing and fixing it.
