### ISSUE TITLE
Batch Sending Issue 

### ISSUE THREAD

**Issue by mkaya93** [Bogardo/Mailgun#94]
Hello @Bogardo ,
I am trying to send batch messages with this code. 
```
Mailgun::send('newproject', $data, function ($message) use ($mail,$brand) { 
        	$message->from('hello@website.com', 'Website');
        	$message->to($mail)->subject($brand. ' Is Waiting your ideas.');
      	});
```

But I got this error when its reaching 1000. 

> You've exceeded the maximum recipient count (1,000) mailgun

So I sent an email to mailgun. And they replied like this. 

> The maximum number of recipients allowed for Batch Sending is 1,000 per API request. So if you have more than that, you will need to create the required batches through your application and send an API request for each batch.

In that case what should I have to do with your packages ?

**Comment by Bogardo** [comment]
You should split your recipients in chunks of 1000.
If you are using a Laravel Collection take a look at: 
https://laravel.com/docs/5.3/collections#method-chunk.

Or, if it's just an array: 
http://php.net/manual/en/function.array-chunk.php

Which would translate to somethink like the following:

```php
foreach ($mail->chunk(1000) as $chunk) {
    Mailgun::send('newproject', $data, function ($message) use ($chunk, $brand) { 
        $message->from('hello@website.com', 'Website');
        $message->to($chunk)->subject($brand. ' Is Waiting your ideas.');
    });
}
```

**Comment by BesimVatan** [comment]
The structure of the directory changes when you use the chunk function.

$mail[0] 
  "besimvatan@gmail.com" => array:3 [
    "name" => "Besim Vatan"
    "gag" => 0.025
    "marka" => "Etkin Kampüs"
  ];

but $mail->chunk(1000) as $chunk

chunk[0] 

 0 => array:3 [
    "name" => "Besim Vatan "
    "gag" => 0.025
    "marka" => "Etkin Kampüs"
  ]

**Comment by Bogardo** [comment]
If you read the docs for `array_chunk` and/or `Collection::chunk` you'll notice you can pass a second parameter `bool $preserve_keys`.

**Comment by BesimVatan** [comment]
@Bogardo  thank you for response
