### ISSUE TITLE
any support for unsubscribe from mailing list?

### ISSUE THREAD

**Issue by vesper8** [Bogardo/Mailgun#96]
I see how to subscribe someone to a mailing list, but is there any support in your package for displaying an unsubscribe link in an email and doing an unsubscribe action when clicked?

**Comment by Bogardo** [comment]
No, unfortunately not. You'll have to implement this yourself.
Either by updating a member of a mailinglist and setting the `subscribed` property to `false` or by deleting the member from the mailinglist completely.
