### ISSUE TITLE
Laravel 5.4 support

### ISSUE THREAD

**Issue by DemianD** [Bogardo/Mailgun#97]
This package brokes when upgrading to L5.4

**Comment by Bogardo** [comment]
I haven't had the time to check for L5.4 compatibility, could you please be a bit more specific about what exactly breaks on L5.4?

**Comment by DemianD** [comment]
[Symfony\Component\Debug\Exception\FatalThrowableError]              
Call to undefined method Illuminate\Foundation\Application::share() 

I'm trying to fix this, and will send a PR later today.

**Comment by DemianD** [comment]
Something wrong with this I guess:

https://github.com/Bogardo/Mailgun/blob/master/src/MailgunServiceProvider.php#L47-L51

Arguments are not passed to the constructor.

`    /**
     * Resolve the given type from the container.
     *
     * @param  string  $abstract
     * @return mixed
     */
    public function make($abstract);`

Using a simple constructor can fix this, but is there a binding for MailgunApi::class?

**Comment by DemianD** [comment]
#98
